### ISSUE TITLE
jupyter widget x-axis

### ISSUE THREAD

**Issue by robambalu** [finos/perspective#1389] opened 2021-04-20 20:50 UTC
Sorry if this is a newb Q but Im having a hard time finding documentation on this.
I got my PerspectiveWidgvet working in jupyterlab.  I have a few questions:
- i have a use case where i will stream data in, starting with no data at all.  I create the widget with an empty data set, but then when the data streams in it seems like the x-axis is out of order ( perhaps its treating the data as strings? but i see no what to pass some sort of schema ):
PerspectiveWidget({ k : [] for k in self._columns + [timecol]},
                                            plugin='y_line',
                                            columns=self._columns,
                                            row_pivots=timecol,
                                            aggregates = { k : 'last' for k in self._columns}
                                            )
- I want to make a chart of timeseries, Im not sure if im configuring it correctly ( see above, with row_pivots and aggregates )

Attached is what the realtime output looks like ( note the x-axis )
![Capture](https://user-images.githubusercontent.com/28680700/115462298-7dd4ee00-a1f8-11eb-9d77-06f8d0b1b232.PNG)

**Comment by sc1f** [comment] 2021-04-20 21:05
The easiest way is to use a table:

```python
table = perspective.Table({"a": float, "b": datetime.datetime}) # etc.
widget = perspective.PerspectiveWidget(table, row_pivots=["b"]) # etc.

# update table with data and widget will automatically pick up
table.update({"a": 1.2345, "b": datetime.datetime.now()})
```
It seems like your dataset is being inferred as strings - the schema should fix that issue. You can also sort by the x axis to make sure that the timestamps are in descending order.

More docs on the schema and data types: https://perspective.finos.org/docs/md/python.html#schemas--supported-data-types

**Comment by robambalu** [comment] 2021-04-20 21:56
Thanks, that does seem to fix the immediate problem, but it introduced a new one.  In my use case not all columns update on every timestamp.  It seems something is now converting these blanks / nulls into 0.0:
![Capture](https://user-images.githubusercontent.com/28680700/115468931-cba22400-a201-11eb-882f-a28a077ef093.PNG)

**Comment by sc1f** [comment] 2021-04-20 22:13
What is the format of your update data? The row-oriented format (`[{"a": 1, "b": 2}, {...]`) works with partial updates (i.e. data[0] has columns a, b, and c whereas data[1] has columns a and b only). It would also work to explicitly mark those cells out as null.

**Comment by robambalu** [comment] 2021-04-20 22:21
it is as you described, say I have columns a,b,c, i may update with dict of a and b but not c
it worked before when I didnt use schema ( but that had the other problem )
When I went with schema, it started pushing 0.0 rather than null.  I would prefer not to push nulls if it can be avoided, its unnecessary overhead on my end

**Comment by nmichaud** [comment] 2021-04-21 01:45
The issue is with the LAST aggregate function. Since you are grouping (bucketing) by time, each group likely only has a single record. The last aggregate doesn't seem to handle the case where a value in the bucket is null.

**Comment by texodus** [comment] 2021-04-23 04:38
This is fixed in #1390 and will be in the `0.7.1` release.  In this particular case, you can also use the `"last by index"` aggregate type, which is identical to `last` and happens to already implement null-awareness correctly in the current release `<=0.7.0`.

Example:

```python
tbl.view(row_pivots=["time"], aggregates={"bid": "last by index", "ask": "last"}, columns=["bid", "ask"]).to_records()
```
```python
[{'__ROW_PATH__': [], 'bid': 100.3, 'ask': None},
 {'__ROW_PATH__': [datetime.datetime(2021, 4, 23, 0, 29, 47, 752000)],
  'bid': 100.1,
  'ask': None},
 {'__ROW_PATH__': [datetime.datetime(2021, 4, 23, 0, 29, 48, 752000)], 
  'bid': 100.3,
  'ask': None}]
```

**Comment by texodus** [comment] 2021-04-23 04:46
If you're still having issues, feel free to re-open or create a new Issue (since Github will close this one automatically with #1390)

**Closed** 2021-04-23 05:08 UTC
Labels: C++, bug

**Comment by robambalu** [comment] 2021-04-23 12:35
Thanks Andrew, confirmed last by index fixed it.  Will keep an eye out for the next release
