### ISSUE TITLE
Unable to run perspective with angular and webpack, webpack example also gives the same error 

### ISSUE THREAD

**Issue by BlackWingedKing** [finos/perspective#1494] opened 2021-07-27 03:06 UTC
### Steps to Reproduce:
Hello, 

thank you for this project, I'm facing some issues running perspective with angular. I have created an minimal working example [here](https://github.com/BlackWingedKing/perspective_mwe_angular/tree/main/perspective-npm-angular) to replicate my issue

my angular project installation details

```
Angular CLI: 12.0.2
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 x64
@angular-devkit/architect    0.1200.2
@angular-devkit/core         12.0.2
@angular-devkit/schematics   12.0.2
@schematics/angular          12.0.2
```

I followed the javascript user guide and created a custom.webpack.config.js for angular and added the following to my custom.webpack.config
```
const PerspectivePlugin = require("@finos/perspective-webpack-plugin");

module.exports = {
  plugins: [new PerspectivePlugin()]
};
```

however when I try to import viewer, viewer-datagrid, viewer-d3fc in my app.component.ts I get the following error
```
./node_modules/regular-table/dist/umd/regular-table.js:655:12 - Error: Module parse failed: Unexpected token (655:12)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
 * ./node_modules/@ngtools/webpack/src/ivy/index.js
You may need an additional loader to handle the result of these loaders.
|         let t = [];
|
>         for await (t of _this.table_model.draw(_this._container_size, _this._view_cache, _this._selected_id, s, h, a)) {
|           _this._is_styling = !0;
|           const e = _this._style_callbacks;

./node_modules/monaco-editor/esm/vs/base/browser/ui/actionbar/actionbar.css - Error: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(1:1) C:\Users\rites\Desktop\temp\perspective-tests\perspective_mwe_angular\perspective-npm-angular\node_modules\monaco-editor\esm\vs\base\browser\ui\actionbar\actionbar.css Unknown word

> 1 | // Imports
    | ^
  2 | import ___CSS_LOADER_API_IMPORT___ from "../../../../../../../css-loader/dist/runtime/api.js";
  3 | var ___CSS_LOADER_EXPORT___ = ___CSS_LOADER_API_IMPORT___(function(i){return i[1]});


./node_modules/monaco-editor/esm/vs/base/browser/ui/aria/aria.css - Error: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

...
```
[fullerror](https://github.com/BlackWingedKing/perspective_mwe_angular/blob/main/perspective-angular-error.txt)

I'm also facing similar error (monaco-editor ...) while running the webpack example using npm/yarn

1. I have added the mwe for the webpack example with npm - [here](https://github.com/BlackWingedKing/perspective_mwe_angular/tree/main/example-webpack-npm), I get this error when I run `npm run start` - [error](https://github.com/BlackWingedKing/perspective_mwe_angular/blob/main/webpack-npm-error.txt)
2. for the webpack example with yarn - [here](https://github.com/BlackWingedKing/perspective_mwe_angular/tree/main/example-webpack-yarn), I get this error when I run `yarn start` - [error](https://github.com/BlackWingedKing/perspective_mwe_angular/blob/main/webpack-yarn-error.txt)

note: both (npm, yarn) webpack example project folders will almost be the same

### Environment:
```
Angular CLI: 12.0.2
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 x64
@angular-devkit/architect    0.1200.2
@angular-devkit/core         12.0.2
@angular-devkit/schematics   12.0.2
@schematics/angular          12.0.2

yarn 1.22.11
```
### Additional Context:
mwe repo can be found [here](https://github.com/BlackWingedKing/perspective_mwe_angular)

**Comment by timkpaine** [comment] 2021-07-27 03:16
https://github.com/finos/perspective/discussions/1484

**Comment by timkpaine** [comment] 2021-07-30 23:12
closing as duplicate of active discussions

**Closed by timkpaine** 2021-07-30 23:12 UTC
Labels: bug, duplicate
