### ISSUE TITLE
`table.remove(keys)` from node seems to corrupt indexing?

### ISSUE THREAD

**Issue by andyferris** [finos/perspective#998] opened 2020-04-03 06:21 UTC
### Steps to Reproduce:
 1. In a node.js backend, we create a new table called `table` and add some rows. We are viewing this in the browser through a seperate frontend app, connecting via websocket.
 2. In the backend, we call `table.remove(keys)` on with one or more keys (a small fraction of the data).
 3. In the browser frontend, using the search functionality to e.g. filter for a particular row (on the value of a primary key, for example) we are shown an incorrect row.

### Expected Result:
The filtered row should obey the filter.

### Actual Result:
Another row is displayed. For example a `==` filter on a primary key displays exactly one row, but it is actually one of the neighboring rows with a different (slightly offset) primary key.

### Environment:
Node 12, Perspective 0.4.6, Google Chrome 80.0.3987.149

### Additional Context:
Reloading the browser window does not fix the problem - so whatever is going on, I suspect it has more to do with the `Table` in node rather than the `View` in the browser.

I haven't yet looked into the implementation of perspective (what's a gnode?)... but given it is so fast, I suspect there are some secondary acceleration indices maintained on the table columns, and the observed behaviour is consistent with these not being updated correctly when a row is removed. E.g. perhaps internally the filter finds the index to a row through the acceleration index, but this is somehow offset to the real data. It doesn't seem to matter which column we filter on - primary key or not (one example had multiple columns that happened to be unique, and filtering on any of them returned the same incorrect row).

Here's an example where `Job.Code` is offset by 2. (I get the same row when I filter on the corresponding `Job.ID` instead).

![image](https://user-images.githubusercontent.com/2974526/78330553-919abb80-75c7-11ea-9c57-eebdd67aee16.png)

**Comment by sc1f** [comment] 2020-04-09 01:46
Are you able to reproduce this issue when the table and view are all in the same browser process? I took a try at recreating the same scenario using the Python library (which shares the internal C++ with the Javascript library), and set up a quick example where rows were being removed every 500ms:

![filters](https://user-images.githubusercontent.com/13220267/78849272-00ba4a80-79e2-11ea-8e68-907628b46103.gif)

As far as I can tell, the behavior seems correct here when filtering across different columns, including the primary key column ("id"). We don't have solid test coverage around how `remove` interops with other operations, so this definitely seems like a real issue, but I bet it's buried deep within the C++ instead of being specific to the node remote binding.

I'll keep doing a little digging and seeing if I can reproduce the issue, but if you have a minimal repro that I can start with/better, a code-only repro that does not use the viewer and can still get the error, that would be awesome. Thanks!

**Comment by sc1f** [comment] 2020-04-09 18:35
I have a hunch about this - are you able to reproduce this error when you use Perspective version 0.4.4? I made a bunch of internal refactors that were merged after that version, and I'm wondering if those changes caused the issue that you were seeing. I'm still unable to reproduce this on the latest version, but if the issue stops happening for you on 0.4.4, then I know exactly what caused the issue. Thanks!

**Comment by andyferris** [comment] 2020-04-27 10:47
Sorry for the delay.

So it's a bit of a pain to try 0.4.4 because we've been relying on 0.4.6 since before we supported deletions on our side, and I haven't found the space and time to play around with that. I also don't have a minimal repro, but it was a symptom we observed with some larger datasets that we had evolving over time (at the time it seemed that all the deletions were causing problems, though).

I'd have to do some work to create tables in the browser process - we don't really do that currently.

> We don't have solid test coverage around how remove interops with other operations

Just in case it wasn't clear, in my case there were no other operations applied other than the filter.

> but I bet it's buried deep within the C++ instead of being specific to the node remote binding.

Yes - I was simply referring to that the issue might be more lilely to be in the Node C++/WASM rather than the browser C++/WASM (since restarting the browser AFTER the corruption did not correct the issue when the data was reloaded from scratch across the websocket).

**Comment by sc1f** [comment] 2021-09-02 18:41
Hi,

Thanks for the report! It turns out that #1505 is a duplicate of this issue, and my reproduction of the issue was off the mark as my example did not use string primary keys, but integer ones instead. The offending code is only triggered with removes on string primary keys, hence my missing the issue in the initial report.

I'll keep this issue open until the PR is merged, but I am confident this bug has been addressed.

**Closed** 2021-09-02 21:41 UTC
Labels: bug, C++
