### ISSUE TITLE
DateTime Comparison Blanks out when the milliseconds is 0

### ISSUE THREAD

**Issue by choandrew** [finos/perspective#1645] opened 2021-12-01 15:11 UTC
## Bug Report

The DateTime Comparison Blanks out when the milliseconds is 0

### Steps to Reproduce:

You can see this in your bl.ocks example
https://bl.ocks.org/texodus/raw/9bec2f8041471bafc2c56db2272a9381/?raw=true

![image](https://user-images.githubusercontent.com/10456364/144257337-dd0baa38-e05c-4244-a69b-98a8dd985329.png)

When you change the 8:05:04.001 in the snap above into 8:05:04.000 (when you type it), it will blank out the entire thing
This is reproducible like 99% of the time

### Expected Result:
DateTime does not blank out

### Actual Result:
The DateTime  blanks out

### Environment:
reproducible in 1.0.0 through 1.0.3

**Comment by texodus** [comment] 2021-12-06 19:11
Thanks for the report @choandrew!  I could not reproduce this error as described but suspect you may be experiencing a race-condition with the `focus` event.  There's a fix for this narrow issue in `1.0.5` - can you please try this release and let us know if you're still experiencing issues related to the datetime filter input in this version.

**Comment by choandrew** [comment] 2021-12-06 20:23
I will try to do a step by step reproduction (I am on chrome 95 on Windows 10)

1) start on the streaming blocks example (https://bl.ocks.org/texodus/raw/9bec2f8041471bafc2c56db2272a9381/?raw=true)
![image](https://user-images.githubusercontent.com/10456364/144914705-8611b0e9-f174-45b1-a5ef-51b2c22a23c9.png)


2) add a MDY filter (in this case, the column is "lastUpdate")
![image](https://user-images.githubusercontent.com/10456364/144914807-ec05e62c-f3ad-48dc-afd7-b2b9799e70e6.png)


3) switch the "==" in the filter to ">="
![image](https://user-images.githubusercontent.com/10456364/144915624-cd615c23-d03b-4f65-82e8-bb284ab84dd5.png)

4) type in a time with a lot of zeros as such (right now, it is 2:22PM, so I will type in 2:00PM)
![image](https://user-images.githubusercontent.com/10456364/144915725-e42b1463-6dc1-4faa-985b-832860a67e60.png)

the second I type in that PM, it will blank out
![image](https://user-images.githubusercontent.com/10456364/144915774-c385126e-a98e-45a8-a3f0-534c933ffbbf.png)



Clicking that calendar button _always_ works so it is a workaround, although it would be nice to be able to type it in

**Closed** 2021-12-23 07:57 UTC
Labels: bug

**Comment by texodus** [comment] 2021-12-23 08:04
Thanks @choandrew.  The issue was not reproducible for me until I finally tried Chrome on Windows.  It turns out `"datetime-local"` values can return a number of different string formats, depending on some internal/timezone/os/browser logic that I don't understand (it does not match how I interpret [rfc3339](https://datatracker.ietf.org/doc/html/rfc3339)).

Nevertheless, I am confident that #1685 finally fixes this issue, it will be release in `1.0.8`

**Comment by choandrew** [comment] 2021-12-23 14:35
Thank you @texodus!
