### ISSUE TITLE
Large string outputs from calculated columns kill persptive viewer

### ISSUE THREAD

**Issue by nickroci** [finos/perspective#1787] opened 2022-04-22 11:59 UTC
To repro, go to persptive streaming example, switch to non grouped view, create a new column outputting around 300 char string then enable it. The longer it is the faster it seems to die. I suspect even smaller strings kill it with enough rows/updates - I think I have observed this with about 30 chars but difficult to repro. I can see that it might slow it down but I don't think it should just hang.

Presume it's in latest version.

Thanks!

**Comment by texodus** [comment] 2022-07-11 15:09
I need more details (a repro) to understand this failure case ... but assuming your expression is indeed producing _unique_ strings, this is a duplicate of #1723.   Note this behavior applies to _all string values everywhere_ in Perspective - otherwise e.g. filters on expression columns would necessitate string equality calculation per tick.

**Comment by nickpholden** [comment] 2022-07-11 15:12
Duplicate

**Closed** 2024-07-05 05:26 UTC
Labels: bug, C++
