### ISSUE TITLE
Outdated Perspective Jupyter docs for 3.0 release

### ISSUE THREAD

**Issue by paddymul** [finos/perspective#2764] opened 2024-09-24 18:53 UTC
### Steps to Reproduce:
```bash
pip install perspective-python jupyter lab
cd examples/jupyter-notebooks
jupyter lab
```
Try the widget tutorial
https://github.com/finos/perspective/blob/28a3101b58773374458fef59de08d179407fa177/examples/jupyter-notebooks/widget_tutorial.ipynb

### Expected Result:
The code runs and imports work with the latest version of perspective.  I think the code probably only works with perspective 2.x

### Actual Result:
```python-traceback
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 from perspective import Table, PerspectiveWidget
      2 from datetime import date, datetime
      3 import pandas as pd

ImportError: cannot import name 'Table' from 'perspective' ([/Users/paddy/anaconda3/envs/perspective-1/lib/python3.12/site-packages/perspective/__init__.py](http://localhost:8892/Users/paddy/anaconda3/envs/perspective-1/lib/python3.12/site-packages/perspective/__init__.py))
```

### Environment:
```python
>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.12.5.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 22.6.0
Version               : Darwin Kernel Version 22.6.0: Wed Oct  4 21:25:40 PDT 2023; root:xnu-8796.141.3.701.17~4/RELEASE_ARM64_T8103
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

```

**Comment by adambouras** [comment] 2024-09-25 01:52
I did also encountered the same error and it looks like the ` Table, PerspectiveWidget` has been removed as well as other related functions. 
```python 
import perspective as psp

dir(psp)

```

**Comment by timkpaine** [comment] 2024-09-26 07:40
Duplicate of https://github.com/finos/perspective/issues/2757

@texodus please deploy the docs, it looks like the website is still out of date

**Closed by timkpaine** 2024-09-26 07:40 UTC

**Comment by texodus** [comment] 2024-09-26 15:02
The up-to-date docs are [now hosted on `docs.rs`](https://docs.rs/perspective-python/latest/perspective_python/). We're going to remove them from the site, but there is a regression in docusaurus that I have not had time to fix yet preventing us from updating this site.

**Comment by timkpaine** [comment] 2024-09-26 15:29
Its quite difficult to see the font there:

<img width="1060" alt="image" src="https://github.com/user-attachments/assets/75c2507f-b801-41fd-a6e0-da84d1df8973">
