### ISSUE TITLE
Perspective + CodeMirror 6 clash after update from 2.10.0 to 2.10.1

### ISSUE THREAD

**Issue by mhkeller** [finos/perspective#2704] opened 2024-08-06 00:15 UTC
## Bug Report

The [original issue](https://github.com/finos/perspective/issues/2635) is locked and I can't post this reproduction there so I'm making a new issue.

### Steps to Reproduce:
Here's a reproduction of [#2635](https://github.com/finos/perspective/issues/2635) 

https://github.com/mhkeller/perspective-codemirror-bug

If you comment out codemirror, perspective loads fine

### Expected Result:

The two load together fine.

### Actual Result:

If you load code mirror 6 with perspective 2.10.1, you get a `RunTimeError: unreachable` error
![error](https://github.com/user-attachments/assets/27aeb654-6c1a-4b9a-8a16-80cdf1a0f3d0)

### Environment:
See reproduction

**Comment by texodus** [comment] 2024-08-06 01:28
Thanks a bunch for the repro @mhkeller!

The issue is due to [a bug in `wasm-bindgen@0.2.87` used by `perspective-viewer@2.10.1`](https://github.com/rustwasm/wasm-bindgen/pull/3808). Upgrading to `perspective-viewer@3.0.0-rc.1` (which already uses a fixed `wasm-bindgen@0.2.91`) or downgrading to `perspective-viewer@2.10.0` are your only options. I've [opened a PR against your sample repo that uses `perspective@3.0.0-rc.1` from `jsdelivr`](https://github.com/mhkeller/perspective-codemirror-bug/pull/1) as an example.

Running your example in debug mode shows the trigger as an assertion failure deep in the memory allocation code - it does not seem to be strictly _related_ to CodeMirror _per se_, more that this specific version of CodeMirror's CSS rules just happen to apply to `perspective-viewer` also, and in parsing the string rules themselves to discover Theme values, this path _happens_ to trip a rare allocation failure.

**Comment by mhkeller** [comment] 2024-08-06 01:39
Awesome thanks for looking at it so quickly. I imagined that with a bump in the major version this would likely be resolved. Do you happen to know which CSS rules are clashing? Could be good for users who have that version of codemirror to try to put something in to mitigate any display or functionality issues.

**Comment by texodus** [comment] 2024-08-06 01:44
It's not exactly a CSS clash - it is a rare string allocation issue that just _happens_ to be triggered by CodeMirror's CSS. It can be mitigated by doing basically _any_ trivial text modification of this file (for example, [Prospective.co](https://prospective.co/) just happens to use a CSS bundler). You may similarly be able to configure parcel to bundle CSS differently.

These aren't _sane_ solutions though - they are just randomizing the input so a rare/random memory bug is avoided.

**Comment by mhkeller** [comment] 2024-08-06 01:55
Got it. Well, on the bright side, the CSS isn’t clashing. I think I’ll keep 2.10.0 for now and wait for 3.0. Any sense of when that will be ready?

**Comment by texodus** [comment] 2024-08-06 02:00
Soon, but [`3.0.0-rc.1` is already available](https://www.npmjs.com/package/@finos/perspective-viewer/v/3.0.0-rc.1) and will the JavaScript libraries will be identical to those released in `3.0.0`. The only things we'll change between now and `3.0.0` are related to the packaging process for JupyterLab.

**Comment by mhkeller** [comment] 2024-08-06 02:06
Ah great. Sounds like a good option then.

**Comment by texodus** [comment] 2024-08-23 15:56
`3.0.0` is now released, closing

**Closed by texodus** 2024-08-23 15:56 UTC

**Comment by mhkeller** [comment] 2024-08-23 16:28
Congrats on the release! I'll try to get it set up with that version. I assume [these docs](https://perspective.finos.org/docs/js/#server-only-via-websocketserver-and-nodejs) are outdated right? I did a quick test when we were talking three weeks ago and ran into an issue where I have to update to esm.

**Comment by texodus** [comment] 2024-08-23 17:42
The docs are up-to-date and they talk about ESM in the [CDN](https://perspective.finos.org/docs/js/#from-cdn) and [bundler](https://perspective.finos.org/docs/js/#esbuild) sections.

There are holes and blindspots befitting a major refactor - let us know if you think something needs to be more clear and we'll update the language.
